from __future__ import annotations

import json
from pathlib import Path

from build_phase6_workflows import (
    code, connect, execute_workflow, http_nebius, http_supabase_rpc, if_true,
    manual, node, respond, sub_trigger, webhook, workflow,
)

ROOT = Path(__file__).resolve().parents[1]
N8N = ROOT / "n8n"


def build_advisory_worker() -> dict:
    supported = ["assumptions_risks", "offer_pricing", "validation_proof", "operating_model",
                 "financial_readiness", "execution_readiness", "launch_distribution",
                 "growth_optimization", "action_blueprint"]
    nodes = [
        manual("Run Advisory Worker Test", -1280, -220),
        code("Create Safe Advisory Fixture", -1060, -220, """return [{json:{task:{id:'00000000-0000-4000-8000-000000000701',task_key:'s2_offer_pricing',module_key:'offer_pricing',goal:'Create evidence-labelled offer and pricing hypotheses.'},idea_text:'A grounded research workspace for founders.',profile_version:1,profile:{goal:{type:'PAID_CUSTOMERS'},constraints:{available_budget:2000,hours_per_week:10}},dependency_outputs:[],correlation_id:'bp-advisory-safe-test',test_mode:true}}];"""),
        sub_trigger("When Called by Typed Router", -1280, 20),
        code("Normalize Advisory Task", -1020, 0, f"""const x=$input.first()?.json??{{}};const t=x.task??x;const supported={json.dumps(supported)};const module=String(t.module_key??'').toLowerCase();const idea=String(x.idea_text??x.profile?.idea_text??'').trim();return [{{json:{{...x,task:t,module_key:module,idea_text:idea,supported:supported.includes(module)&&idea.length>=10,profile_version:Number(x.profile_version??t.profile_version??0),dependency_outputs:Array.isArray(x.dependency_outputs)?x.dependency_outputs:[],test_mode:x.test_mode===true,correlation_id:String(x.correlation_id??`bp-advisory-${{Date.now()}}`).slice(0,200)}}}}];"""),
        if_true("Advisory Route Supported?", -800, 0, "={{ $json.supported }}"),
        if_true("Use Safe Advisory Fixture?", -580, -100, "={{ $json.test_mode }}"),
        code("Return Safe Advisory Result", -340, -220, """const x=$json;return [{json:{schema_version:'bp-task-worker-result-v1',task_id:x.task.id,task_key:x.task.task_key,module_key:x.module_key,status:'COMPLETED',observation:{verdict:'VALID',summary:`Safe fixture completed ${x.module_key}.`,output:{schema_version:'bp-advisory-section-v1',module_key:x.module_key,executive_finding:'Safe structural fixture only.',recommendations:[],contextual_actions:[],risks:[],unknowns:['Production evidence intentionally omitted.'],assumptions:['Synthetic test output.'],limitations:['TEST_MODE'],coverage:0},evidence_ids:[],limitations:['TEST_MODE'],retryable:false,proposed_route:'OBSERVE_AND_UNLOCK'},correlation_id:x.correlation_id,test_mode:true}}];"""),
        if_true("Deterministic Finance?", -340, -40, "={{ $json.module_key === 'financial_readiness' }}"),
        code("Build Deterministic Finance Scenarios", -100, -160, """const x=$json;const p=x.profile??{};const c=p.constraints??p.founder_inputs??{};const n=v=>Number.isFinite(Number(v))&&Number(v)>=0?Number(v):null;const budget=n(c.available_budget??c.money_available);const monthly=n(c.monthly_build_budget);const price=n(c.target_monthly_price??c.price);const fixed=n(c.estimated_monthly_fixed_cost);const hours=n(c.hours_per_week);const scenarios=[];if(price&&fixed!=null)scenarios.push({name:'Founder-input break-even',formula:'estimated_monthly_fixed_cost / target_monthly_price',result_customers:Math.ceil(fixed/price),inputs:{estimated_monthly_fixed_cost:fixed,target_monthly_price:price}});if(budget!=null&&monthly)scenarios.push({name:'Cash runway',formula:'available_budget / monthly_build_budget',result_months:Number((budget/monthly).toFixed(1)),inputs:{available_budget:budget,monthly_build_budget:monthly}});if(budget!=null)scenarios.push({name:'Maximum committed budget',formula:'founder-entered available_budget',result_budget:budget,inputs:{available_budget:budget}});const missing=[];if(budget==null)missing.push('available_budget');if(!monthly)missing.push('monthly_build_budget');if(!price)missing.push('target_monthly_price');if(fixed==null)missing.push('estimated_monthly_fixed_cost');const needsInput=budget==null;const output={schema_version:'bp-financial-readiness-v1',module_key:x.module_key,executive_finding:scenarios.length?'Founder-input scenarios are available; they are not forecasts.':'No financial result is calculated until the founder supplies an available budget.',scenarios,founder_capacity:{hours_per_week:hours},missing_inputs:missing,contextual_actions:missing.length?[{title:'Add the missing financial inputs',why:`Required for more complete transparent scenarios: ${missing.join(', ')}`}]:[{title:'Validate price before treating break-even as useful',why:'The price is a founder hypothesis until real payment evidence exists.'}],risks:['Scenario outputs change directly with founder-entered assumptions.'],unknowns:missing,assumptions:[],limitations:['Scenario, not forecast. No revenue, conversion, or willingness-to-pay value was invented.'],coverage:missing.length?Math.max(0.25,1-missing.length/4):1};return [{json:{schema_version:'bp-task-worker-result-v1',task_id:x.task.id,task_key:x.task.task_key,module_key:x.module_key,status:needsInput?'PARTIAL':'COMPLETED',observation:{verdict:needsInput?'NEEDS_INPUT':'VALID',summary:output.executive_finding,output,evidence_ids:[],limitations:output.limitations,retryable:false,proposed_route:needsInput?'FOUNDER_INPUT':'OBSERVE_AND_UNLOCK'},correlation_id:x.correlation_id,test_mode:false}}];"""),
        if_true("Execution Readiness Gate?", -100, 40, "={{ $json.module_key === 'execution_readiness' }}"),
        code("Prepare Execution Readiness", 140, -20, """const x=$json;const deps=x.dependency_outputs??[];const required=deps.map(d=>String(d.module_key)).filter(Boolean);const completed=deps.filter(d=>['COMPLETED','REUSED','NOT_APPLICABLE'].includes(String(d.status))||d.observation_verdict==='VALID').map(d=>String(d.module_key));const coverages=deps.map(d=>Number(d.output?.coverage)).filter(Number.isFinite);const coverage=coverages.length?coverages.reduce((a,b)=>a+b,0)/coverages.length:(completed.length/Math.max(1,required.length));const risks=deps.flatMap(d=>Array.isArray(d.output?.risks)?d.output.risks:[]).filter(r=>/critical|blocking|fatal/i.test(typeof r==='string'?r:JSON.stringify(r))).slice(0,10);const explanation=`${completed.length} of ${required.length} required advisory modules completed; evidence coverage ${Math.round(coverage*100)}%; ${risks.length} critical risks remain.`;return [{json:{...x,readiness:{required,completed,coverage,risks,explanation},rpc_body:{p_run_id:x.run_id,p_profile_version:x.profile_version,p_completed_modules:completed,p_required_modules:required,p_evidence_coverage:Math.max(0,Math.min(1,coverage)),p_open_critical_risks:risks,p_explanation:explanation}}}];"""),
        http_supabase_rpc("Persist Execution Readiness and Gate 2", "persist_execution_readiness", 380, -20),
        code("Wrap Execution Readiness Observation", 620, -20, """const x=$('Prepare Execution Readiness').first().json;const p=$json??{};const ok=p.persisted===true&&p.checkpoint_id;const output={schema_version:'bp-execution-readiness-v1',module_key:'execution_readiness',executive_finding:ok?`${p.verdict} (${p.score}/100).`:'Gate 2 could not be persisted safely.',...x.readiness,verdict:p.verdict??'UNKNOWN',score:p.score??null,checkpoint_id:p.checkpoint_id??null,available_decisions:p.available_decisions??[],contextual_actions:[{title:'Review Gate 2',why:'A founder decision is required before the Action Blueprint can be created.'}],limitations:['Readiness is a deterministic decision aid, not proof of business success.']};return [{json:{schema_version:'bp-task-worker-result-v1',task_id:x.task.id,task_key:x.task.task_key,module_key:x.module_key,status:ok?'COMPLETED':'PARTIAL',observation:{verdict:ok?'VALID':'TOOL_FAILED',summary:output.executive_finding,output,evidence_ids:[],limitations:output.limitations,retryable:!ok,proposed_route:ok?'HUMAN_CHECKPOINT':'BOUNDED_RETRY_OR_FALLBACK'},correlation_id:x.correlation_id,test_mode:false}}];"""),
        code("Prepare Grounded Advisory Analysis", 140, 140, """const x=$json;const roles={assumptions_risks:'Re-rank assumptions, contradictions, and critical risks.',offer_pricing:'Create offer, packaging, and pricing hypotheses. Pricing is a testable hypothesis, never willingness-to-pay fact.',validation_proof:'Design the smallest founder-run validation experiments with explicit pass, fail, and inconclusive thresholds.',operating_model:'Advise on feasible delivery and operating choices inside the supplied time, budget, and team constraints.',launch_distribution:'Advise on MVP boundary, first-customer routes, distribution options, and milestone sequence. Do not execute a launch or create weekly schedules.',growth_optimization:'Provide growth prerequisites based only on measured traction. If traction is absent, state prerequisites and unknowns only.',action_blueprint:'Synthesize an advisory Action Blueprint with MVP boundary, first-customer route, distribution, financial scenarios, milestones, risks, and explicit unknowns.'};const deps=(x.dependency_outputs??[]).map(d=>({task_key:d.task_key,module_key:d.module_key,status:d.status,output:d.output,route_reason:d.route_reason}));return [{json:{...x,request:{model:'Qwen/Qwen3-235B-A22B-Instruct-2507',temperature:0.05,max_tokens:x.module_key==='action_blueprint'?2600:1500,response_format:{type:'json_object'},messages:[{role:'system',content:`You are Blueprint's bounded ${x.module_key} advisory agent. ${roles[x.module_key]} Use only founder profile and supplied dependency outputs. Separate evidence, inferences, assumptions, risks, and unknowns. Never invent customers, quotes, market sizes, conversion, retention, revenue, willingness to pay, or completed actions. Never contact, send, publish, buy, book, pay, or delete. Return JSON with executive_finding, recommendations, contextual_actions [{title,why}], risks, unknowns, assumptions, limitations. For action_blueprint also return stages and milestones; milestones are outcome-level, not weekly tasks.`},{role:'user',content:JSON.stringify({idea:x.idea_text,goal:x.profile?.goal??null,founder_profile:x.profile??{},dependencies:deps})}]}}}];"""),
        http_nebius("Nebius — Bounded Advisory Agent", 380, 140, 45000),
        code("Enforce Advisory Contract", 620, 140, r"""const x=$('Prepare Grounded Advisory Analysis').first().json;const r=$json??{};const c=r.choices?.[0]?.message?.content;let a=null;try{a=typeof c==='string'?JSON.parse(c.replace(/^```json\s*|\s*```$/g,'')):c}catch{}if(!a)return [{json:{schema_version:'bp-task-worker-result-v1',task_id:x.task.id,task_key:x.task.task_key,module_key:x.module_key,status:'PARTIAL',observation:{verdict:'TOOL_FAILED',summary:'The advisory model failed safely; no unsupported output was accepted.',output:{},evidence_ids:[],limitations:['Existing completed work remains preserved.'],retryable:true,proposed_route:'BOUNDED_RETRY_OR_FALLBACK'},correlation_id:x.correlation_id,test_mode:false}}];const output={schema_version:x.module_key==='action_blueprint'?'bp-action-blueprint-v1':'bp-advisory-section-v1',module_key:x.module_key,executive_finding:String(a.executive_finding??''),recommendations:Array.isArray(a.recommendations)?a.recommendations:[],contextual_actions:Array.isArray(a.contextual_actions)?a.contextual_actions.slice(0,5):[],risks:Array.isArray(a.risks)?a.risks:[],unknowns:Array.isArray(a.unknowns)?a.unknowns:[],assumptions:Array.isArray(a.assumptions)?a.assumptions:[],limitations:Array.isArray(a.limitations)?a.limitations:[],stages:Array.isArray(a.stages)?a.stages:[],milestones:Array.isArray(a.milestones)?a.milestones:[],dependency_snapshot:(x.dependency_outputs??[]).map(d=>({task_key:d.task_key,module_key:d.module_key,status:d.status})),coverage:1};return [{json:{...x,advisory_output:output,model:r.model??null,is_action_blueprint:x.module_key==='action_blueprint'}}];"""),
        if_true("Persist Action Blueprint?", 860, 140, "={{ $json.is_action_blueprint }}"),
        code("Prepare Immutable Action Blueprint", 1100, 40, """const x=$json;const bp={...x.advisory_output,product_idea:x.idea_text,starting_position:x.profile??{},generated_from_run:x.run_id,advisory_only:true};return [{json:{...x,action_blueprint:bp,rpc_body:{p_run_id:x.run_id,p_profile_version:x.profile_version,p_version_kind:'ACTION',p_artifact_stage:'ACTION_BLUEPRINT',p_status:'COMPLETED',p_blueprint:bp,p_change_summary:'Stage 2 evidence and Gate 2 decision produced the advisory Action Blueprint.',p_source_verdict_ids:[]}}}];"""),
        http_supabase_rpc("Persist Immutable Action Blueprint", "create_progressive_blueprint_version", 1340, 40),
        code("Wrap Persisted Action Blueprint", 1580, 40, """const x=$('Prepare Immutable Action Blueprint').first().json;const p=$json??{};const ok=p.id&&p.version_kind==='ACTION';return [{json:{schema_version:'bp-task-worker-result-v1',task_id:x.task.id,task_key:x.task.task_key,module_key:x.module_key,status:ok?'COMPLETED':'PARTIAL',observation:{verdict:ok?'VALID':'TOOL_FAILED',summary:ok?`Action Blueprint v${p.version} created.`:'The Action Blueprint was generated but immutable persistence failed.',output:{...x.action_blueprint,blueprint_version:p.version??null,blueprint_version_id:p.id??null},evidence_ids:[],limitations:x.action_blueprint.limitations??[],retryable:!ok,proposed_route:ok?'OBSERVE_AND_UNLOCK':'BOUNDED_RETRY_OR_FALLBACK'},correlation_id:x.correlation_id,test_mode:false}}];"""),
        code("Wrap Advisory Observation", 1100, 240, """const x=$json;return [{json:{schema_version:'bp-task-worker-result-v1',task_id:x.task.id,task_key:x.task.task_key,module_key:x.module_key,status:'COMPLETED',observation:{verdict:'VALID',summary:x.advisory_output.executive_finding||`${x.module_key} completed.`,output:x.advisory_output,evidence_ids:[],limitations:x.advisory_output.limitations,retryable:false,proposed_route:'OBSERVE_AND_UNLOCK'},provider_trace:[{provider:'NEBIUS',status:'SUCCEEDED',model:x.model}],correlation_id:x.correlation_id,test_mode:false}}];"""),
        code("Refuse Unsupported Advisory Route", -580, 180, f"""const x=$json;return [{{json:{{schema_version:'bp-task-worker-result-v1',task_id:x.task?.id??null,task_key:x.task?.task_key??'',module_key:x.module_key,status:'SAFE_FAILED',observation:{{verdict:'POLICY_DENIED',summary:'No allowlisted advisory worker exists for this route.',output:{{supported_modules:{json.dumps(supported)}}},evidence_ids:[],limitations:['Nothing was executed outside the worker boundary.'],retryable:false,proposed_route:'SUPERVISOR_REPLAN'}},correlation_id:x.correlation_id,test_mode:x.test_mode}}}}];"""),
    ]
    c = {}
    connect(c,"Run Advisory Worker Test","Create Safe Advisory Fixture"); connect(c,"Create Safe Advisory Fixture","Normalize Advisory Task")
    connect(c,"When Called by Typed Router","Normalize Advisory Task"); connect(c,"Normalize Advisory Task","Advisory Route Supported?")
    connect(c,"Advisory Route Supported?","Use Safe Advisory Fixture?",0); connect(c,"Advisory Route Supported?","Refuse Unsupported Advisory Route",1)
    connect(c,"Use Safe Advisory Fixture?","Return Safe Advisory Result",0); connect(c,"Use Safe Advisory Fixture?","Deterministic Finance?",1)
    connect(c,"Deterministic Finance?","Build Deterministic Finance Scenarios",0); connect(c,"Deterministic Finance?","Execution Readiness Gate?",1)
    connect(c,"Execution Readiness Gate?","Prepare Execution Readiness",0); connect(c,"Prepare Execution Readiness","Persist Execution Readiness and Gate 2"); connect(c,"Persist Execution Readiness and Gate 2","Wrap Execution Readiness Observation")
    connect(c,"Execution Readiness Gate?","Prepare Grounded Advisory Analysis",1); connect(c,"Prepare Grounded Advisory Analysis","Nebius — Bounded Advisory Agent"); connect(c,"Nebius — Bounded Advisory Agent","Enforce Advisory Contract"); connect(c,"Enforce Advisory Contract","Persist Action Blueprint?")
    connect(c,"Persist Action Blueprint?","Prepare Immutable Action Blueprint",0); connect(c,"Prepare Immutable Action Blueprint","Persist Immutable Action Blueprint"); connect(c,"Persist Immutable Action Blueprint","Wrap Persisted Action Blueprint")
    connect(c,"Persist Action Blueprint?","Wrap Advisory Observation",1)
    return workflow("bpStage23Advisory01","BP-STAGE23-01 Advisory and Action Blueprint",nodes,c,180)


def build_checkpoint_api() -> dict:
    verify = node("Verify Checkpoint Supabase User","n8n-nodes-base.httpRequest",-520,-80,{"url":"https://gudsbrmphrokpnzmrlqd.supabase.co/auth/v1/user","authentication":"genericCredentialType","genericAuthType":"httpHeaderAuth","sendHeaders":True,"headerParameters":{"parameters":[{"name":"Authorization","value":"={{ $json.authorization }}"}]},"options":{"timeout":15000}},4.5)
    verify["credentials"]={"httpHeaderAuth":{"id":"fguxqwSfKfj2xfo9","name":"BP Supabase Public"}}; verify["onError"]="continueRegularOutput"
    nodes=[
        webhook("POST Blueprint Checkpoint","blueprint/checkpoint",-1180,0),
        code("Validate Checkpoint API Request",-960,0,r"""const raw=$input.first()?.json??{};let b=raw.body??raw;if(typeof b==='string'){try{b=JSON.parse(b)}catch{b={}}}const h=Object.fromEntries(Object.entries(raw.headers??{}).map(([k,v])=>[String(k).toLowerCase(),v]));const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const authorization=String(h.authorization??'');const decision=String(b.decision??'').toUpperCase();const allowed=['PROCEED','TARGETED_VALIDATION','RUN_MISSING_RESEARCH','CONTINUE_ANYWAY','PAUSE_OR_REVISE','CANCEL'];const valid=/^Bearer\s+\S+$/i.test(authorization)&&uuid.test(String(b.checkpoint_id??''))&&Number(b.expected_state_version)>0&&allowed.includes(decision);return [{json:{valid,status_code:/^Bearer\s+\S+$/i.test(authorization)?400:401,authorization,checkpoint_id:b.checkpoint_id??null,expected_state_version:Number(b.expected_state_version??0),decision,decision_payload:b.decision_payload&&typeof b.decision_payload==='object'?b.decision_payload:{},run_id:b.run_id??null,project_id:b.project_id??null,profile_version:Number(b.profile_version??0),idea_text:String(b.idea_text??''),profile:b.profile??{},requested_research:Array.isArray(b.requested_research)?b.requested_research:[],correlation_id:String(b.correlation_id??`bp-checkpoint-${Date.now()}`).slice(0,200)}}];"""),
        if_true("Checkpoint API Request Valid?",-740,0,"={{ $json.valid }}"),verify,
        if_true("Checkpoint User Authenticated?",-300,-80,"={{ Boolean($json.id) }}"),
        code("Prepare Durable Checkpoint Resolution",-60,-160,"""const x=$('Validate Checkpoint API Request').first().json;return [{json:{...x,test_mode:false}}];"""),
        execute_workflow("Resolve Through BP-HITL-01","bpHitl01CheckpointResume",180,-160),
        if_true("Checkpoint Requires Replan?",420,-160,"={{ Boolean($json.planner_input) && $json.status === 'RESOLVED' }}"),
        code("Prepare Resume Supervisor Dispatch",660,-240,"""const r=$json;const x=$('Validate Checkpoint API Request').first().json;return [{json:{command:'RESUME',authorization:x.authorization,project_id:x.project_id,run_id:r.planner_input?.run_id??x.run_id,profile_version:x.profile_version,idea_text:x.idea_text,profile:x.profile,founder_inputs:x.profile?.constraints??{},requested_research:x.requested_research,planning_mode:r.planner_input.planning_mode,gate_context:r.planner_input.gate_context,controller_cycle:0,correlation_id:x.correlation_id,test_mode:false,resolution:r}}];"""),
        execute_workflow("Resume Dynamic Supervisor","bp00Supervisor",900,-240),
        code("Build Resumed Checkpoint Response",1140,-240,"""const s=$json;const x=$('Prepare Resume Supervisor Dispatch').first().json;return [{json:{status_code:202,response:{ok:true,status:s.status??'PLANNING',route:s.route??'TASK_PLANNER',decision:x.resolution.decision,planning_mode:x.planning_mode,run_id:x.run_id,state_version:x.resolution.state_version,message:s.message??'The next Blueprint stage was dispatched.',poll_after_ms:2000,correlation_id:x.correlation_id}}}];"""),
        code("Build Paused Checkpoint Response",660,-60,"""const r=$json;return [{json:{status_code:r.status==='RESOLVED'?200:409,response:{ok:r.status==='RESOLVED',status:r.status,route:r.route,decision:r.decision,state_version:r.state_version,message:r.status==='RESOLVED'?'The founder decision was recorded; no autonomous stage was started.':'The checkpoint could not be resolved safely.',correlation_id:r.correlation_id}}}];"""),
        respond("Respond Checkpoint",1380,-120,"={{ JSON.stringify($json.response) }}"),
        respond("Respond Invalid Checkpoint Request",-520,140,"={{ JSON.stringify({ok:false,error_code:$json.status_code===401?'UNAUTHENTICATED':'INVALID_CHECKPOINT_REQUEST',message:$json.status_code===401?'The private demo session is missing or expired.':'Refresh the gate and choose an allowed decision.'}) }}"),
        respond("Respond Invalid Checkpoint Session",-60,80,"={{ JSON.stringify({ok:false,error_code:'UNAUTHENTICATED',message:'The private demo session is invalid or expired.'}) }}","={{ 401 }}"),
    ]
    c={}; connect(c,"POST Blueprint Checkpoint","Validate Checkpoint API Request"); connect(c,"Validate Checkpoint API Request","Checkpoint API Request Valid?"); connect(c,"Checkpoint API Request Valid?","Verify Checkpoint Supabase User",0); connect(c,"Checkpoint API Request Valid?","Respond Invalid Checkpoint Request",1); connect(c,"Verify Checkpoint Supabase User","Checkpoint User Authenticated?"); connect(c,"Checkpoint User Authenticated?","Prepare Durable Checkpoint Resolution",0); connect(c,"Checkpoint User Authenticated?","Respond Invalid Checkpoint Session",1); connect(c,"Prepare Durable Checkpoint Resolution","Resolve Through BP-HITL-01"); connect(c,"Resolve Through BP-HITL-01","Checkpoint Requires Replan?"); connect(c,"Checkpoint Requires Replan?","Prepare Resume Supervisor Dispatch",0); connect(c,"Prepare Resume Supervisor Dispatch","Resume Dynamic Supervisor"); connect(c,"Resume Dynamic Supervisor","Build Resumed Checkpoint Response"); connect(c,"Build Resumed Checkpoint Response","Respond Checkpoint"); connect(c,"Checkpoint Requires Replan?","Build Paused Checkpoint Response",1); connect(c,"Build Paused Checkpoint Response","Respond Checkpoint")
    return workflow("bpApi03Checkpoint","BP-API-03 Founder Checkpoint and Resume",nodes,c,900)


def patch_existing() -> None:
    planner_path=N8N/"BP-PLAN-01-dynamic-task-planner.json"; w=json.loads(planner_path.read_text(encoding="utf-8"))
    planner=next(n for n in w["nodes"] if n["name"]=="Normalize Profile and Build Candidate Graph")
    old="const goal=src.goal&&typeof src.goal==='object'?src.goal:(src.profile?.goal&&typeof src.profile.goal==='object'?src.profile.goal:null);const goalStatus=String(src.goal_status??src.profile?.goal_status??(goal?'CONFIRMED':'MISSING')).toUpperCase();"
    new="const rawGoal=src.goal??src.profile?.goal??null;const goalAliases={startup:'VALIDATE_DEMAND',just_explore:'VALIDATE_DEMAND',side_income:'SIDE_INCOME',small_business:'PAID_CUSTOMERS',raise_money:'FUNDRAISING_READINESS',get_job:'CUSTOM',test_whether_idea_can_work:'VALIDATE_DEMAND'};const goal=rawGoal&&typeof rawGoal==='object'?rawGoal:(typeof rawGoal==='string'&&rawGoal.trim()?{type:goalAliases[rawGoal]??String(rawGoal).toUpperCase(),label:rawGoal}:null);const goalStatus=String(src.goal_status??src.profile?.goal_status??(goal?'CONFIRMED':'MISSING')).toUpperCase();"
    planner["parameters"]["jsCode"]=planner["parameters"]["jsCode"].replace(old,new)
    planner_path.write_text(json.dumps(w,indent=2)+"\n",encoding="utf-8")

    scheduler_path=N8N/"BP-SCHED-01-eligible-task-scheduler.json"; w=json.loads(scheduler_path.read_text(encoding="utf-8"))
    n=next(n for n in w["nodes"] if n["name"]=="Normalize Scheduler Request")
    n["parameters"]["jsCode"]=r"""const src=$input.first()?.json??{};const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const mode=String(src.planning_mode??'DISCOVER').toUpperCase();const allowed=mode==='PROVE_AND_DESIGN'?['assumptions_risks','offer_pricing','validation_proof','operating_model','financial_readiness','execution_readiness']:mode==='COMPLETE_ACTION_BLUEPRINT'?['launch_distribution','growth_optimization','action_blueprint']:['foundation','customer_demand','competitor_intelligence','market_economics','evidence_audit','research_verdict','final_blueprint'];const authorization=String(src.authorization??'');const runId=src.run_id??null;const testMode=src.test_mode===true;const canClaim=!testMode&&uuid.test(String(runId??''))&&/^Bearer\s+\S+$/i.test(authorization);return [{json:{schema_version:'bp-scheduler-request-v1',authorization,owner_id:src.owner_id??null,project_id:src.project_id??null,run_id:runId,profile_version:Number(src.profile_version??0),idea_text:String(src.idea_text??src.profile?.idea_text??''),profile:src.profile??{},requested_research:Array.isArray(src.requested_research)?src.requested_research:[],provided_tasks:Array.isArray(src.tasks)?src.tasks:[],allowed_modules:allowed,claim_limit:Math.max(1,Math.min(3,Math.trunc(Number(src.claim_limit??3)))),controller_cycle:Math.max(0,Math.trunc(Number(src.controller_cycle??0))),can_claim:canClaim,test_mode:testMode,correlation_id:String(src.correlation_id??`bp-scheduler-${Date.now()}`).slice(0,200)}}];"""
    scheduler_path.write_text(json.dumps(w,indent=2)+"\n",encoding="utf-8")

    router_path=N8N/"BP-STAGE1-ROUTER-01.json"; w=json.loads(router_path.read_text(encoding="utf-8"))
    normalize=next(n for n in w["nodes"] if n["name"]=="Normalize Typed Route")
    normalize["parameters"]["jsCode"]=normalize["parameters"]["jsCode"].replace("'final_blueprint']","'final_blueprint','assumptions_risks','offer_pricing','validation_proof','operating_model','financial_readiness','execution_readiness','launch_distribution','growth_optimization','action_blueprint']")
    refuse=next(n for n in w["nodes"] if n["name"]=="Refuse Unknown Worker Route")
    advisory_if=if_true("Stage 2 or 3 Advisory Route?",refuse["position"][0]-240,refuse["position"][1],"={{ ['assumptions_risks','offer_pricing','validation_proof','operating_model','financial_readiness','execution_readiness','launch_distribution','growth_optimization','action_blueprint'].includes($json.module_key) }}")
    advisory_run=execute_workflow("Run Stage 2 or 3 Advisory Worker","bpStage23Advisory01",refuse["position"][0],refuse["position"][1]-120)
    if not any(n["name"]=="Stage 2 or 3 Advisory Route?" for n in w["nodes"]):
        w["nodes"].extend([advisory_if,advisory_run])
    previous="Research Blueprint Route?"; w["connections"][previous]["main"][1]=[{"node":"Stage 2 or 3 Advisory Route?","type":"main","index":0}]
    w["connections"]["Stage 2 or 3 Advisory Route?"]={"main":[[{"node":"Run Stage 2 or 3 Advisory Worker","type":"main","index":0}],[{"node":"Refuse Unknown Worker Route","type":"main","index":0}]]}
    router_path.write_text(json.dumps(w,indent=2)+"\n",encoding="utf-8")

    controller_path=N8N/"BP-00-adaptive-supervisor.json"; w=json.loads(controller_path.read_text(encoding="utf-8"))
    normalize=next(n for n in w["nodes"] if n["name"]=="Normalize Canonical Supervisor Command")
    normalize["parameters"]["jsCode"]=r"""const src=$input.first()?.json??{};const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const authorization=String(src.authorization??'').trim();const command=String(src.command??'START').toUpperCase();const aliases={user_research:'customer_demand',customer_research:'customer_demand',customer_demand:'customer_demand',competitor_research:'competitor_intelligence',competitor_intelligence:'competitor_intelligence',market_research:'market_economics',market_economics:'market_economics'};const selected=[...new Set((Array.isArray(src.requested_research)?src.requested_research:[]).map(x=>aliases[String(x).toLowerCase()]).filter(Boolean))];const planningMode=String(src.planning_mode??'DISCOVER').toUpperCase();const valid=['START','RESUME'].includes(command)&&['DISCOVER','PROVE_AND_DESIGN','COMPLETE_ACTION_BLUEPRINT'].includes(planningMode)&&uuid.test(String(src.project_id??''))&&uuid.test(String(src.run_id??''))&&Number(src.profile_version)>0&&/^Bearer\s+\S+$/i.test(authorization)&&selected.length>0;return [{json:{...src,command,authorization,requested_research:selected,planning_mode:planningMode,profile_version:Number(src.profile_version??0),controller_cycle:Math.max(0,Math.trunc(Number(src.controller_cycle??0))),claim_limit:1,force_replan:command==='RESUME',valid,error_code:valid?null:'INVALID_CANONICAL_COMMAND',safe_message:valid?'Authenticated dynamic orchestration accepted.':'The orchestration command is incomplete, so no autonomous work was dispatched.'}}];"""
    bind=next(n for n in w["nodes"] if n["name"]=="Bind Prepared Run State")
    bind["parameters"]["jsCode"]="""const base=$('Prepare Dynamic Run State').first().json;const raw=$input.first()?.json??{};const ok=raw.prepared===true&&raw.run&&raw.run.id===base.run_id;const shouldPlan=ok&&(base.force_replan===true||raw.should_plan===true);return [{json:{...base,prepare_ok:ok,prepared:raw,should_plan:shouldPlan,can_work:ok&&!raw.terminal&&!raw.waiting_for_human,controller_status:ok?(raw.waiting_for_human?'WAITING_APPROVAL':raw.terminal?raw.run.status:'PLANNING'):'HUMAN_REVIEW',controller_route:ok?(raw.waiting_for_human?'HITL_RESUME':raw.terminal?'COMPLETE':'TASK_PLANNER'):'HUMAN_REVIEW',requires_human:!ok||raw.waiting_for_human===true,terminal:raw.terminal===true,message:ok?'Dynamic run state prepared.':'The supervisor could not prepare durable run state; the run was stopped safely.',provider_response:ok?undefined:raw}}];"""
    sched=next(n for n in w["nodes"] if n["name"]=="Build Scheduler Request")
    sched["parameters"]["jsCode"]="""const x=$json;return [{json:{authorization:x.authorization,owner_id:x.owner_id,project_id:x.project_id,run_id:x.run_id,profile_version:x.profile_version,idea_text:x.idea_text,profile:x.profile??x.founder_inputs??{},requested_research:x.requested_research,planning_mode:x.planning_mode,gate_context:x.gate_context??{},claim_limit:1,controller_cycle:Number(x.controller_cycle??0),correlation_id:x.correlation_id,test_mode:false}}];"""
    controller_path.write_text(json.dumps(w,indent=2)+"\n",encoding="utf-8")

    chat_path=N8N/"BP-CHAT-01-research-copilot.json"; w=json.loads(chat_path.read_text(encoding="utf-8"))
    validate=next(n for n in w["nodes"] if n["name"]=="Validate Chat Request and Scope")
    validate["parameters"]["jsCode"]=validate["parameters"]["jsCode"].replace("context:raw.context??null}}];","section_key:String(b.section_key??'').toLowerCase()||null,context:raw.context??null}}];")
    answer=next(n for n in w["nodes"] if n["name"]=="Prepare Grounded Copilot Answer")
    answer["parameters"]["jsCode"]=answer["parameters"]["jsCode"].replace("{message:x.message,intent:x.intent,context}","{message:x.message,intent:x.intent,requested_section:x.section_key,context}")
    answer["parameters"]["jsCode"]=answer["parameters"]["jsCode"].replace("Answer only from the supplied run", "Focus first on requested_section when supplied. Answer only from the supplied run")
    chat_path.write_text(json.dumps(w,indent=2)+"\n",encoding="utf-8")

    audit_path=N8N/"BP-AUDIT-01-independent-evidence-auditor.json"; w=json.loads(audit_path.read_text(encoding="utf-8"))
    audit=next(n for n in w["nodes"] if n["name"]=="Audit Evidence Independently")
    audit_code=audit["parameters"]["jsCode"]
    audit_code=audit_code.replace(
        "dimensions[dim]={score,coverage,evidence_ids:cards.map(x=>String(x.evidence_id)),unknowns:unknowns.map(String).slice(0,20)};",
        "const directEvidenceTypes=new Set(['FOUNDER','INTERVIEW','PAYMENT','PURCHASE','PREORDER','DEPOSIT','SIGNUP','COMMITMENT','BEHAVIOR']);const directEvidenceCount=cards.filter(c=>{const provider=String(c.provider??c.source_provider??'').toUpperCase();const type=String(c.evidence_type??c.source_type??c.signal_type??'').toUpperCase();return provider==='FOUNDER'||directEvidenceTypes.has(type)}).length;dimensions[dim]={score,coverage,evidence_ids:cards.map(x=>String(x.evidence_id)),unknowns:unknowns.map(String).slice(0,20),direct_evidence_count:directEvidenceCount,evidence_basis:directEvidenceCount?'PRIMARY_OR_BEHAVIORAL':'DESK_RESEARCH_ONLY'};",
    )
    audit_code=audit_code.replace(
        "const evidenceCoverage=relevant.length?Math.round(totalCoverage/relevant.length*100)/100:0;",
        "const demandDirect=Number(dimensions.user_demand?.direct_evidence_count??0);const directDemandGap=!src.test_mode&&Boolean(dimensions.user_demand)&&demandDirect===0;if(directDemandGap){dimensions.user_demand.score=Math.min(Number(dimensions.user_demand.score)||0,20);if(dimensions.competitive_opportunity)dimensions.competitive_opportunity.score=Math.min(Number(dimensions.competitive_opportunity.score)||0,65);if(dimensions.market_accessibility)dimensions.market_accessibility.score=Math.min(Number(dimensions.market_accessibility.score)||0,65);}const evidenceCoverage=relevant.length?Math.round(totalCoverage/relevant.length*100)/100:0;",
    )
    audit_code=audit_code.replace(
        "const auditStatus=!blockers.length&&!missing.length&&evidenceCoverage>=0.60?'PASS':'NOT_PASSED';",
        "const auditStatus=!blockers.length&&!missing.length&&evidenceCoverage>=0.60?'PASS':'NOT_PASSED';if(directDemandGap)blockers.push('customer_demand: desk research found directional signals, but no direct interview, commitment, signup, deposit, purchase, payment, or behavioral evidence validates demand for this specific idea.');",
    )
    audit["parameters"]["jsCode"]=audit_code
    audit_path.write_text(json.dumps(w,indent=2)+"\n",encoding="utf-8")


def main() -> None:
    (N8N/"BP-STAGE23-01-advisory-action-blueprint.json").write_text(json.dumps(build_advisory_worker(),indent=2)+"\n",encoding="utf-8")
    (N8N/"BP-API-03-founder-checkpoint.json").write_text(json.dumps(build_checkpoint_api(),indent=2)+"\n",encoding="utf-8")
    patch_existing()


if __name__ == "__main__":
    main()
